In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import os as ana_ani_ops
import warnings as ana_ani_usrwrng
ana_ani_usrwrng.filterwarnings('ignore')
import librosa as ana_animal_Elbr
import librosa.display as ana_ani_lbrdisp
import matplotlib.pyplot as ana_animalplt
import IPython.display as ana_animalipd
import random as ana_animalRand

In [ ]:
import numpy as ana_animal_nmp
from sklearn.model_selection import train_test_split as ana_anitrs
from imblearn.over_sampling import SMOTE as animalSmttt
from tqdm import tqdm
import joblib

# Define the Animal Emotions Data
ana_animal_emopath = '/content/drive/MyDrive/'
ana_animal_emotion = ['Animal Anger', 'Animal Bur', 'Animal Disgust', 'Animal Fear']

# Extracting MFCC features
def animal_extract_mfcc(audio_data, sr=22050, n_mfcc=13):
    animal_mfcc_features = []
    for y in tqdm(audio_data, desc="\nExtracting MFCCs for Animal Emotions"):
        ani_mfcc = ana_animal_Elbr.feature.mfcc(y=y, sr=sr, n_mfcc=n_mfcc)
        ani_mfcc = ana_animal_nmp.mean(ani_mfcc, axis=1)
        animal_mfcc_features.append(ani_mfcc)
    return ana_animal_nmp.array(animal_mfcc_features)


In [ ]:
# Generating spectrograms for animal emotions
def ana_animal_Eaudio(ana_animal_emopath, ana_ani_emotions, sample_rate=22050):
    animaldata, animallabels = [], []
    for animalEmotion in ana_ani_emotions:
        animalEmotion_pat = ana_ani_ops.path.join(ana_animal_emopath, animalEmotion)
        if ana_ani_ops.path.exists(animalEmotion_pat):
            animalfiles = [f for f in ana_ani_ops.listdir(animalEmotion_pat) if f.endswith('.wav')]
            for animalfile in tqdm(animalfiles, desc=f"Loading {animalEmotion}"):
                animalfile_path = ana_ani_ops.path.join(animalEmotion_pat, animalfile)
                animaly, animalsr = ana_animal_Elbr.load(animalfile_path, sr=sample_rate)
                animaldata.append(animaly)
                animallabels.append(animalEmotion)
    return animaldata, animallabels

In [ ]:
# Loading data with extracted features
animalaudio_data, animalaudio_labels = ana_animal_Eaudio(ana_animal_emopath, ana_animal_emotion)

# Convert labels to numeric
animallabel_index = {label: i for i, label in enumerate(ana_animal_emotion)}
animalnumeric_labels = ana_animal_nmp.array([animallabel_index[animallabel] for animallabel in animalaudio_labels])

Loading Animal Fear: 100%|██████████| 4/4 [00:01<00:00,  2.47it/s]


In [ ]:
animalaudio_data

[array([ 0.        ,  0.        ,  0.        , ..., -0.00368966,
        -0.00435532, -0.00326866], dtype=float32),
 array([ 2.7266536e-03, -1.6277190e-05, -3.6877219e-03, ...,
         2.0297308e-02,  2.2992481e-02,  2.3672318e-02], dtype=float32),
 array([ 0.        ,  0.        ,  0.        , ...,  0.00186121,
         0.00086656, -0.00286455], dtype=float32),
 array([0.        , 0.        , 0.        , ..., 0.02029732, 0.0229925 ,
        0.02367233], dtype=float32),
 array([ 0.        ,  0.        ,  0.        , ..., -0.01916187,
        -0.01824912, -0.01078008], dtype=float32),
 array([ 0.        ,  0.        ,  0.        , ..., -0.00703238,
        -0.00979534, -0.00631683], dtype=float32),
 array([0.00679429, 0.00958945, 0.00751768, ..., 0.04624031, 0.0448653 ,
        0.04662009], dtype=float32),
 array([0.        , 0.        , 0.        , ..., 0.00550992, 0.00611939,
        0.00849918], dtype=float32),
 array([0.        , 0.        , 0.        , ..., 0.02438279, 0.02648311,

In [ ]:
animalaudio_labels

['Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Anger',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Bur',
 'Animal Disgust',
 'Animal Disgust',
 'Animal Disgust',
 'Animal Fear',
 'Animal Fear',
 'Animal Fear',
 'Animal Fear']

In [ ]:
animalnumeric_labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3])

In [ ]:
from collections import Counter as animalCnntrr
animal_features = animal_extract_mfcc(animalaudio_data)

# Apply SMOTE for balancing
animal_class_counts = animalCnntrr(animalnumeric_labels)
print(f"\nClass distribution in training set before SMOTE: {animal_class_counts}")

animal_smoteM = animalSmttt(random_state=15, k_neighbors=2)
animalX, animalY = animal_smoteM.fit_resample(animal_features, animalnumeric_labels)

print(f"Class distribution in training set after SMOTE: {animalCnntrr(animalY)}")


Extracting MFCCs for Animal Emotions: 100%|██████████| 41/41 [00:03<00:00, 11.60it/s]


Class distribution in training set before SMOTE: Counter({1: 18, 0: 16, 3: 4, 2: 3})
Class distribution in training set after SMOTE: Counter({0: 18, 1: 18, 2: 18, 3: 18})


In [ ]:
animal_features.shape

(41, 13)

In [ ]:
# Splitting for 80-10-10
animalX_tan, animalX_tes, animalY_tan, animalY_tes = ana_anitrs(animalX, animalY, test_size=0.2, random_state=15)
animalX_val, animalX_tes, animalY_val, animalY_tes = ana_anitrs(animalX_tes, animalY_tes, test_size=0.5, random_state=15)
print("Training Set =",animalX_tan.shape, "Validation Set =", animalX_val.shape, "Testing Set =",animalX_tes.shape)

Training Set = (57, 13) Validation Set = (7, 13) Testing Set = (8, 13)


In [ ]:
# Generating spectrograms for CNN
def animal_spectrograms(audio_data, window_size, hop_length):
    ani_spectrograms = []
    animal_max_len = 0  # Initialize max_len to store maximum spectrogram length

    for animaly in tqdm(audio_data, desc="\nGenerating Spectrograms"):
        animalS = ana_animal_Elbr.feature.melspectrogram(y=animaly, sr=22050, n_fft=window_size, hop_length=hop_length)
        animalS_dB = ana_animal_Elbr.power_to_db(animalS, ref=ana_animal_nmp.max)

        # Update max_len if current spectrogram is longer
        animal_max_len = max(animal_max_len, animalS_dB.shape[1])

        ani_spectrograms.append(animalS_dB)

    # Pad spectrograms to the maximum length
    animalpadded_spectrograms = []
    for ani_spec in ani_spectrograms:
        pad_width = animal_max_len - ani_spec.shape[1]

        # Pad with zeros to the right
        ani_padded_spec = ana_animal_nmp.pad(ani_spec, pad_width=((0, 0), (0, pad_width)), mode='constant')
        animalpadded_spectrograms.append(ani_padded_spec)

    return ana_animal_nmp.array(animalpadded_spectrograms)

# Applying spectrograms for CNN models
aniXtr_spec_2048 = animal_spectrograms(animalX_tan, window_size=2048, hop_length=1024)
aniXval_spec_2048 = animal_spectrograms(animalX_val, window_size=2048, hop_length=1024)
aniXtst_spec_2048 = animal_spectrograms(animalX_tes, window_size=2048, hop_length=1024)

aniXtr_spec_1024 = animal_spectrograms(animalX_tan, window_size=1024, hop_length=512)
aniXval_spec_1024 = animal_spectrograms(animalX_val, window_size=1024, hop_length=512)
aniXtst_spec_1024 = animal_spectrograms(animalX_tes, window_size=1024, hop_length=512)

# Reshaping CNN input
aniXtr_spec_2048 = aniXtr_spec_2048[..., ana_animal_nmp.newaxis]
aniXval_spec_2048 = aniXval_spec_2048[..., ana_animal_nmp.newaxis]
aniXtst_spec_2048 = aniXtst_spec_2048[..., ana_animal_nmp.newaxis]

aniXtr_spec_1024 = aniXtr_spec_1024[..., ana_animal_nmp.newaxis]
aniXval_spec_1024 = aniXval_spec_1024[..., ana_animal_nmp.newaxis]
aniXtst_spec_1024 = aniXtst_spec_1024[..., ana_animal_nmp.newaxis]


Generating Spectrograms: 100%|██████████| 57/57 [00:00<00:00, 97.55it/s]

Generating Spectrograms: 100%|██████████| 7/7 [00:00<00:00, 83.20it/s]

Generating Spectrograms: 100%|██████████| 8/8 [00:00<00:00, 116.53it/s]

Generating Spectrograms: 100%|██████████| 57/57 [00:00<00:00, 109.33it/s]

Generating Spectrograms: 100%|██████████| 7/7 [00:00<00:00, 109.44it/s]

Generating Spectrograms: 100%|██████████| 8/8 [00:00<00:00, 110.67it/s]


In [ ]:
import tensorflow as ana_animal_tsf
from tensorflow import keras as ana_animal_krs
from tensorflow.keras import layers, models
from sklearn.metrics import classification_report as ana_animal_clfrp

def create_cnn_animal(input_shape, num_layers):
    animal_modelCNN = models.Sequential()
    animal_modelCNN.add(layers.Conv2D(32, (3, 3), activation='relu', padding='same', input_shape=input_shape))
    animal_modelCNN.add(layers.MaxPooling2D((2, 1)))

    for _ in range(num_layers):
        animal_modelCNN.add(layers.Conv2D(64, (3, 3), activation='relu', padding='same'))
        animal_modelCNN.add(layers.MaxPooling2D((2, 1)))

    animal_modelCNN.add(layers.Flatten())
    animal_modelCNN.add(layers.Dense(128, activation='relu'))
    animal_modelCNN.add(layers.Dense(len(animalY), activation='softmax'))

    animal_modelCNN.compile(optimizer='rmsprop', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    return animal_modelCNN

if aniXtr_spec_2048.shape[-1] == 1:  # Ensure 3D shape
    aniXtr_spec_2048 = aniXtr_spec_2048.reshape(aniXtr_spec_2048.shape[0], 128, -1, 1)
    aniXval_spec_2048 = aniXval_spec_2048.reshape(aniXval_spec_2048.shape[0], 128, -1, 1)

# Train CNN models
ani_cnn_models = {
    "CNN_3_layers": create_cnn_animal(aniXtr_spec_2048.shape[1:], 3),
    "CNN_4_layers": create_cnn_animal(aniXtr_spec_2048.shape[1:], 4),
    "CNN_5_layers": create_cnn_animal(aniXtr_spec_2048.shape[1:], 5),
}

for ani_name, ani_model in ani_cnn_models.items():
    print(f"\nValidating {ani_name}:")
    ani_model.fit(aniXtr_spec_2048, animalY_tan, validation_data=(aniXval_spec_2048, animalY_val), epochs=20, batch_size=16)
    animalY_pred = ani_model.predict(aniXval_spec_2048)
    animalY_pred = ana_animal_nmp.argmax(animalY_pred, axis=1)
    print(ana_animal_clfrp(animalY_val, animalY_pred))
    ani_model.save(f"/content/drive/MyDrive/{ani_name}.keras")


Validating CNN_3_layers:
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 110ms/step - accuracy: 0.1111 - loss: 4.1847 - val_accuracy: 0.7143 - val_loss: 2.2036
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.3620 - loss: 2.5381 - val_accuracy: 0.4286 - val_loss: 1.5173
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4247 - loss: 1.5624 - val_accuracy: 0.2857 - val_loss: 1.7761
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3682 - loss: 1.4850 - val_accuracy: 0.5714 - val_loss: 0.9022
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.4705 - loss: 1.1309 - val_accuracy: 0.0000e+00 - val_loss: 1.6837
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.3076 - loss: 1.4130 - val_accuracy: 0.7143 - val_loss: 1.0379
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6297 - loss: 0.9621 - val_accuracy: 0.2857 - val_loss: 1.1363
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - accuracy: 0.5587 - loss: 1.2957 - val_accur

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         2
           1       1.00      1.00      1.00         1
           2       0.67      1.00      0.80         4

    accuracy                           0.71         7
   macro avg       0.56      0.67      0.60         7
weighted avg       0.52      0.71      0.60         7


Validating CNN_5_layers:
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 3s 134ms/step - accuracy: 0.0866 - loss: 4.1984 - val_accuracy: 0.0000e+00 - val_loss: 2.7327
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.4390 - loss: 2.3760 - val_accuracy: 0.0000e+00 - val_loss: 1.5577
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 0.2735 - loss: 1.4542 - val_accuracy: 0.5714 - val_loss: 1.3988
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.3586 - loss: 1.4664 - val_accuracy: 0.1429 - val_loss: 1.5709
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/s

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 167ms/step
              precision    recall  f1-score   support

           0       0.67      1.00      0.80         2
           1       1.00      1.00      1.00         1
           2       1.00      0.75      0.86         4

    accuracy                           0.86         7
   macro avg       0.89      0.92      0.89         7
weighted avg       0.90      0.86      0.86         7



In [ ]:
for ani_name, ani_model in ani_cnn_models.items():
    print(f"\nTesting {ani_name}:")
    ani_model.fit(aniXtr_spec_2048, animalY_tan, validation_data=(aniXtst_spec_2048, animalY_tes), epochs=20, batch_size=16)


Testing CNN_3_layers:
Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.9384 - loss: 0.2789 - val_accuracy: 0.8750 - val_loss: 0.2593
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - accuracy: 0.8368 - loss: 0.5304 - val_accuracy: 0.8750 - val_loss: 0.1398
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.7538 - loss: 0.4527 - val_accuracy: 1.0000 - val_loss: 0.1065
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - accuracy: 0.8878 - loss: 0.4015 - val_accuracy: 1.0000 - val_loss: 0.0842
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.9589 - loss: 0.1993 - val_accuracy: 1.0000 - val_loss: 0.1729
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.9714 - loss: 0.1931 - val_accuracy: 1.0000 - val_loss: 0.0336
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.7099 - loss: 0.7854 - val_accuracy: 1.0000 - val_loss: 0.0727
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - accuracy: 0.9539 - loss: 0.2074 - val_accuracy: 1.0

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score as ana_ani_accscr, classification_report as ana_ani_clrp

animalX_tan_mfcc = animal_extract_mfcc(animalX_tan)
animalX_valmfcc = animal_extract_mfcc(animalX_val)
animalX_tes_mfcc = animal_extract_mfcc(animalX_tes)

# Training RF classifier
rf_Animalmodel = RandomForestClassifier(n_estimators=80, random_state=15)
rf_Animalmodel.fit(animalX_tan_mfcc, animalY_tan)
joblib.dump(rf_Animalmodel, "/content/drive/MyDrive/AnimalEmotion_RFmodel.pkl")

Animaly_pred = rf_Animalmodel.predict(animalX_valmfcc)
AnimalRFAcc = ana_ani_accscr(animalY_val, Animaly_pred)
print("\nClassification Report for Validation:\n", ana_ani_clrp(animalY_val, Animaly_pred))

Animaly_pred = rf_Animalmodel.predict(animalX_tes_mfcc)
AnimalRFAcc = ana_ani_accscr(animalY_tes, Animaly_pred)
print("\nClassification Report for Testing:\n", ana_ani_clrp(animalY_tes, Animaly_pred))


Extracting MFCCs for Animal Emotions: 100%|██████████| 57/57 [00:00<00:00, 159.22it/s]

Extracting MFCCs for Animal Emotions: 100%|██████████| 7/7 [00:00<00:00, 158.64it/s]

Extracting MFCCs for Animal Emotions: 100%|██████████| 8/8 [00:00<00:00, 170.29it/s]



Classification Report for Validation:
               precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       1.00      1.00      1.00         1
           2       0.80      1.00      0.89         4

    accuracy                           0.86         7
   macro avg       0.93      0.83      0.85         7
weighted avg       0.89      0.86      0.84         7


Classification Report for Testing:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         1
           1       1.00      1.00      1.00         3
           2       1.00      1.00      1.00         3
           3       1.00      1.00      1.00         1

    accuracy                           1.00         8
   macro avg       1.00      1.00      1.00         8
weighted avg       1.00      1.00      1.00         8

